SPEC_SID = '353'
SEED_COUNT = 10_0000
SSR_RATE = 1
SP_RATE = 0.25


FATE_SECRET = '1122'

# sidekiq_redis查询间隔，单位：秒
SIDEKIQ_REDIS_POLL_INTERVAL = (ENV["SIDEKIQ_REDIS_POLL_INTERVAL"] || 0.1).to_f

# sidekiq_redis查询超时时间，单位：秒
SIDEKIQ_REDIS_POLL_TIMEOUT = (ENV["SIDEKIQ_REDIS_POLL_TIMEOUT"] || 1).to_f

SIDEKIQ_REDIS_POLL_COUNT = SIDEKIQ_REDIS_POLL_TIMEOUT / SIDEKIQ_REDIS_POLL_INTERVAL

QUEUES = (ENV["QUEUES"] || 'verify').split(',')


SUMMON_MODE_SSR = 'SSR'
SUMMON_MODE_SP = 'SP'
SUMMON_MODE_SJ = 'SJ'