# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/face_api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pb/face_api.proto", :syntax => :proto3) do
    add_message "pb.FaceVerifyRequest" do
      optional :img1, :bytes, 1
      optional :img2, :bytes, 2
    end
    add_message "pb.FaceVerifyResponse" do
      optional :code, :int32, 1
      optional :score, :float, 2
      optional :message, :string, 3
    end
    add_message "pb.ObjectFeature" do
      optional :type, :string, 1
      optional :version, :int32, 2
      optional :flags, :int32, 3
      optional :blob, :bytes, 4
    end
    add_message "pb.FaceExtractRequest" do
      optional :img, :bytes, 1
    end
    add_message "pb.FaceExtractResponse" do
      optional :code, :int32, 1
      optional :blob, :bytes, 2
      optional :message, :string, 3
    end
    add_message "pb.FeatVerifyRequest" do
      optional :feat1, :bytes, 1
      optional :feat2, :bytes, 2
    end
    add_message "pb.FeatVerifyResponse" do
      optional :code, :int32, 1
      optional :score, :float, 2
      optional :message, :string, 3
    end
  end
end

module Pb
  FaceVerifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.FaceVerifyRequest").msgclass
  FaceVerifyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.FaceVerifyResponse").msgclass
  ObjectFeature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.ObjectFeature").msgclass
  FaceExtractRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.FaceExtractRequest").msgclass
  FaceExtractResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.FaceExtractResponse").msgclass
  FeatVerifyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.FeatVerifyRequest").msgclass
  FeatVerifyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.FeatVerifyResponse").msgclass
end
