# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pb/face_api.proto for package 'pb'

require 'grpc'

module Pb
  module FaceApi
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pb.FaceApi'

      rpc :FaceVerify, ::Pb::FaceVerifyRequest, ::Pb::FaceVerifyResponse
      rpc :FaceExtract, ::Pb::FaceExtractRequest, ::Pb::FaceExtractResponse
      rpc :FeatVerify, ::Pb::FeatVerifyRequest, ::Pb::FeatVerifyResponse
    end

    Stub = Service.rpc_stub_class
  end
end
