# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pwi.proto for package 'pb'

require 'grpc'

module Pb
  module PwiApi
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'pb.PwiApi'

      rpc :GetUserRoles, ::Pb::GetUserRolesArg, ::Pb::GetUserRolesRes
    end

    Stub = Service.rpc_stub_class
  end
end
