# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pwi.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("pwi.proto", :syntax => :proto3) do
    add_message "pb.GetUserRolesArg" do
      optional :userid, :int32, 1
      optional :type, :int32, 2
      optional :table, :string, 3
      optional :attr, :string, 4
      optional :key, :string, 5
    end
    add_message "pb.GetUserRolesRes" do
      optional :code, :int32, 1
      optional :roles, :string, 2
    end
  end
end

module Pb
  GetUserRolesArg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.GetUserRolesArg").msgclass
  GetUserRolesRes = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.GetUserRolesRes").msgclass
end
